quarkus:
    package:
        type: mutable-jar
    live-reload:
        password: abc123
    container-image:
        build: true
        push: true
        group: wlopezob
    kubernetes:
        namespace: default
        replicas: 1
        node-port: #30005
        ports:
            https:
                container-port: 8443
            debug:
                container-port: 5005
        deployment-target: kubernetes
        env:
            vars:
                quarkus-launch-devmode: true
                java-enable-debug: true
                #custom.message: k8s-local-variable
            configmaps: config-ms-servicios-juntos
        service-type: node-port
    kubernetes-client:
        trust-certs: true
      

mconfiguracion:
    mensaje: ${MCONFIGURATION.MENSAJE:"hola"}
mconfiguracion:
    mensaje02: mensaje02